using System;using System.Collections.Generic;
namespace ValheimMastery{internal static class MasterIdolSeatRosterGuard{
internal const double StabilitySeconds=35;
private sealed class Entry{internal Dictionary<string,string> Roster;internal double Changed;}
private static readonly Dictionary<string,Entry> Homes=new Dictionary<string,Entry>(StringComparer.Ordinal);private static ZNet Session;private static ZDOMan Manager;private static ulong Generation;private static readonly List<string> Dead=new List<string>(128);
private static void Current(){if(Session==ZNet.instance&&Manager==ZDOMan.instance&&Generation==MasterIdolLoadIdentity.Generation)return;Homes.Clear();Session=ZNet.instance;Manager=ZDOMan.instance;Generation=MasterIdolLoadIdentity.Generation;}
internal static bool Same(IDictionary<string,string> a,IDictionary<string,string> b){if(a==null||b==null||a.Count!=b.Count)return false;foreach(var row in a)if(!b.TryGetValue(row.Key,out string family)||family!=row.Value)return false;return true;}
internal static bool Stable(string home,IDictionary<string,string> roster,double now){Current();if(home==null||roster==null||roster.Count<1||roster.Count>8||double.IsNaN(now)||double.IsInfinity(now))return false;if(!Homes.TryGetValue(home,out var entry)){if(Homes.Count>=128){Dead.Clear();foreach(var row in Homes)if(MasterIdolEffectZones.Find(row.Key)==null)Dead.Add(row.Key);foreach(var id in Dead)Homes.Remove(id);if(Homes.Count>=128)return false;}entry=new Entry{Roster=new Dictionary<string,string>(roster,StringComparer.Ordinal),Changed=now};Homes.Add(home,entry);return false;}if(!Same(entry.Roster,roster)){entry.Roster=new Dictionary<string,string>(roster,StringComparer.Ordinal);entry.Changed=now;}if(now<entry.Changed){entry.Changed=now;return false;}return now-entry.Changed>=StabilitySeconds;}
internal static void ObserveProjection(MasterIdolEffectGeometry geometry){Current();if(geometry==null||Session==null)return;Dead.Clear();foreach(var row in Homes)if(!geometry.ById.TryGetValue(row.Key,out var zone)||zone.Type!="BlackForest"||zone.Residents.Count==0)Dead.Add(row.Key);foreach(var id in Dead)Homes.Remove(id);double now=Session.GetTimeSeconds();foreach(var zone in geometry.ById.Values)if(zone.Type=="BlackForest"&&zone.Residents.Count>0)Stable(zone.Id,zone.Residents,now);}
internal static bool Stable(MasterIdolEffectZone home){var current=home==null?null:MasterIdolEffectZones.Find(home.Id);if(current==null||!Same(home.Residents,current.Residents))return false;return Stable(home.Id,current.Residents,ZNet.instance.GetTimeSeconds());}
}}
