using System;using System.Collections.Generic;using UnityEngine;
namespace ValheimMastery{
internal static class MasterIdolResidentSpacing{
 private sealed class Spot{internal ZDO Data;internal long Owner;internal ushort Revision;internal string Nonce;internal Vector3 Point;internal double Until;internal bool Work;}
 private static readonly Dictionary<string,Dictionary<string,Spot>> Homes=new Dictionary<string,Dictionary<string,Spot>>(StringComparer.Ordinal);private static ZNet Session;private static ZDOMan Manager;private static ulong Generation;private static double NextPrune;private static readonly List<string> DeadHomes=new List<string>(128),DeadActors=new List<string>(8);
 private static void Current(){if(Session!=ZNet.instance||Manager!=ZDOMan.instance||Generation!=MasterIdolLoadIdentity.Generation){Homes.Clear();Session=ZNet.instance;Manager=ZDOMan.instance;Generation=MasterIdolLoadIdentity.Generation;NextPrune=0;}if(Session==null||Manager==null||Session.GetTimeSeconds()<NextPrune)return;NextPrune=Session.GetTimeSeconds()+5;DeadHomes.Clear();foreach(var home in Homes){DeadActors.Clear();foreach(var actor in home.Value)if(!Live(actor.Key,actor.Value))DeadActors.Add(actor.Key);foreach(var uid in DeadActors)home.Value.Remove(uid);if(home.Value.Count==0)DeadHomes.Add(home.Key);}foreach(var home in DeadHomes)Homes.Remove(home);}
 private static bool Live(string uid,Spot spot){return spot.Until>ZNet.instance.GetTimeSeconds()&&ReferenceEquals(ZDOMan.instance.GetZDO(spot.Data.m_uid),spot.Data)&&spot.Data.GetOwner()==spot.Owner&&spot.Data.OwnerRevision==spot.Revision;}
 internal static void Put(Character actor,string home,string nonce,Vector3 point,double until,bool work){Current();if(!MasterIdolResidentPolicy.TryHome(actor,out var zone)||zone.Id!=home||!zone.Contains(point))return;string uid=actor.m_nview.GetZDO().m_uid.ToString();if(!Homes.TryGetValue(home,out var list)){if(Homes.Count>=128)return;Homes[home]=list=new Dictionary<string,Spot>(StringComparer.Ordinal);}if(list.Count>=8&&!list.ContainsKey(uid))return;var data=actor.m_nview.GetZDO();list[uid]=new Spot{Data=data,Owner=data.GetOwner(),Revision=data.OwnerRevision,Nonce=nonce,Point=point,Until=until,Work=work};}
 internal static void Remove(Character actor,string home,string nonce){Current();if(actor?.m_nview?.GetZDO()==null||home==null||!Homes.TryGetValue(home,out var list))return;string uid=actor.m_nview.GetZDO().m_uid.ToString();if(list.TryGetValue(uid,out var spot)&&(nonce==null||spot.Nonce==nonce))list.Remove(uid);if(list.Count==0)Homes.Remove(home);}
 internal static bool Allowed(Character actor,MasterIdolEffectZone zone,Vector3 point,bool socialEvent){Current();if(!socialEvent){foreach(var member in zone.Residents){if(!MasterIdolNetworkQuota.TryUid(member.Key,out long user,out uint id))continue;var other=ZNetScene.instance?.FindInstance(new ZDOID(user,id))?.GetComponent<Character>();if(other!=null&&other!=actor&&(other.transform.position-point).sqrMagnitude<16)return false;}}if(!Homes.TryGetValue(zone.Id,out var list))return true;string self=actor.m_nview.GetZDO().m_uid.ToString();foreach(var entry in list){if(entry.Key==self||!Live(entry.Key,entry.Value))continue;if(entry.Value.Work&&(entry.Value.Point-point).sqrMagnitude<16)return false;if(!socialEvent&&(entry.Value.Point-point).sqrMagnitude<16)return false;}return true;}
 internal static bool MustYield(Character actor,MasterIdolEffectZone zone,Vector3 goal,out bool work){Current();work=false;if(!Homes.TryGetValue(zone.Id,out var list))return false;string self=actor.m_nview.GetZDO().m_uid.ToString();foreach(var entry in list){if(entry.Key==self||!Live(entry.Key,entry.Value))continue;var spot=entry.Value;if(spot.Work&&(spot.Point-actor.transform.position).sqrMagnitude<16){work=true;return true;}if(!spot.Work&&string.CompareOrdinal(entry.Key,self)<0&&(spot.Point-goal).sqrMagnitude<16)return true;}return false;}
 internal static int Rank(Character actor,MasterIdolEffectZone zone){string uid=actor.m_nview.GetZDO().m_uid.ToString();int rank=0;foreach(var member in zone.Residents)if(string.CompareOrdinal(member.Key,uid)<0)rank++;return rank;}
 internal static string Describe(){Current();return "spacing homes="+Homes.Count+" maxHomes128/maxResidents8 areaRadius4m priority=light-worker/deterministicUID";}
}
}
