using System;using UnityEngine;
namespace ValheimMastery{
internal sealed class MasterIdolResidentPresentation:MonoBehaviour{
 private Animator Animator;private RuntimeAnimatorController Original;private AnimatorOverrideController Override;private AnimationClip Clip;private Character Creature;private BaseAI Ai;private ZNetView View;private ZDO Data;private long Owner;private ushort OwnerRevision;private ZDOMan Manager;private ZNet Session;private ulong Generation;private string Home;private float End;private bool Active,Aftercare;private string LastDecision="not-attempted";
 internal static bool ResourcesReady(Character actor,bool poison){var controller=actor?.GetComponentInChildren<Animator>()?.runtimeAnimatorController??ZNetScene.instance?.GetPrefab("Greydwarf_Shaman")?.GetComponentInChildren<Animator>(true)?.runtimeAnimatorController;if(controller==null)return false;string name=poison?"Standing 2H Magic Attack 04":"Standing 1H Cast Spell 01";bool idle=false,clip=false;foreach(var animation in controller.animationClips){if(animation.name=="Standing Idle")idle=true;if(animation.name==name&&Mathf.Abs(animation.length-(poison?3.333333f:2.266667f))<.05f)clip=true;}return idle&&clip;}
 private static readonly int Movement=unchecked((int)3885065915u);
 internal bool Playing=>Active;
 internal bool BlocksWork=>Active&&!Aftercare;
 internal bool BeginAftercare(float elapsed,string home)
 {if(Active)return false;try{bool started=Begin(false,elapsed,home);Aftercare=started;return started;}
  catch(Exception){try{Stop();}catch(Exception){MasterIdolResidentMetrics.Count("cue.aftercare-cleanup-failed");}return Denied("aftercare-begin-failed");}}
 internal void StopAftercare(){if(Aftercare)Stop();}
 private bool Peaceful=>Creature!=null&&Ai!=null&&!MasterIdolSocialSeats.Battle(Ai,Creature)&&!Ai.IsSleeping()&&!Creature.InDodge()&&!Creature.InEmote()&&GetComponent<MasterIdolSocialSeats>()?.Active!=true&&GetComponent<MasterIdolWelcome>()?.IsPresenting!=true;
 internal bool Begin(bool poison,float elapsed,string home){Stop();if(SystemInfo.graphicsDeviceType==UnityEngine.Rendering.GraphicsDeviceType.Null)return Denied("headless");if(!MasterIdolActivity.Near(transform.position))return Denied("distant");Creature=GetComponent<Character>();Ai=GetComponent<BaseAI>();View=GetComponent<ZNetView>();Animator=GetComponentInChildren<Animator>();if(!Peaceful)return Denied("not-peaceful");if(View?.IsValid()!=true||Animator==null)return Denied("view-or-animator");if(!MasterIdolResidentPolicy.Shaman(Creature,out var zone)||zone.Id!=home)return Denied("source");Original=Animator.runtimeAnimatorController;if(Original==null||!Animator.HasState(0,Movement))return Denied("movement-state");AnimationClip idle=null,source=null;string donor=poison?"Standing 2H Magic Attack 04":"Standing 1H Cast Spell 01";foreach(var animation in Original.animationClips){if(animation.name=="Standing Idle")idle=animation;if(animation.name==donor)source=animation;}if(idle==null||source==null)return Denied("clip");if(elapsed<0||elapsed>=source.length)return Denied("elapsed");Clip=Instantiate(source);Clip.name="VM_EventlessResidentCue";Clip.hideFlags=HideFlags.DontSave;Clip.events=Array.Empty<AnimationEvent>();Override=new AnimatorOverrideController(Original);Override[idle]=Clip;Data=View.GetZDO();Owner=Data.GetOwner();OwnerRevision=Data.OwnerRevision;Manager=ZDOMan.instance;Session=ZNet.instance;Generation=MasterIdolLoadIdentity.Generation;Home=home;End=Time.unscaledTime+source.length-elapsed;Animator.runtimeAnimatorController=Override;Animator.SetFloat("forward_speed",0);Animator.SetFloat("turn_speed",0);Animator.Play(Movement,0,elapsed/source.length);Active=true;LastDecision=poison?"poison-playing":"heal-playing";MasterIdolResidentMetrics.Count(poison?"cue.poison-start":"cue.heal-start");return true;}
 private void Update(){if(!Active)return;if(Time.unscaledTime>=End||Aftercare&&MasterIdolResidentWork.Busy(Creature)||!Peaceful||!MasterIdolActivity.Near(transform.position)||Animator==null||!ReferenceEquals(Animator.runtimeAnimatorController,Override)||Session!=ZNet.instance||Manager!=ZDOMan.instance||Generation!=MasterIdolLoadIdentity.Generation||View?.IsValid()!=true||!ReferenceEquals(View.GetZDO(),Data)||Data.GetOwner()!=Owner||Data.OwnerRevision!=OwnerRevision||!MasterIdolResidentPolicy.Shaman(Creature,out var zone)||zone.Id!=Home){Stop();return;}if(View.IsOwner())Ai.StopMoving();HoldBlend();}
 private bool Denied(string reason){LastDecision=reason;MasterIdolResidentMetrics.Count("cue.denied."+reason);return false;}
 private void HoldBlend(){if(Active&&Animator!=null&&ReferenceEquals(Animator.runtimeAnimatorController,Override)){Animator.SetFloat("forward_speed",0);Animator.SetFloat("turn_speed",0);}}
 private void LateUpdate()=>HoldBlend();
 internal string Describe()=>"cue active="+Active+" decision="+LastDecision+" VFXenabled="+MasteryPlugin.Settings.EnablePerkProcVFX.Value+" remaining="+Math.Max(0,End-Time.unscaledTime);
 internal void Stop(){Active=Aftercare=false;if(Animator!=null&&Override!=null&&ReferenceEquals(Animator.runtimeAnimatorController,Override))Animator.runtimeAnimatorController=Original;if(Override!=null)Destroy(Override);if(Clip!=null)Destroy(Clip);Override=null;Clip=null;Original=null;}
 private void OnDisable()=>Stop();private void OnDestroy()=>Stop();
 internal static void Refuelled(Fireplace fire,float before,float after){if(fire==null||after<=before||fire.m_nview?.IsOwner()!=true)return;try{var donor=fire.m_fuelAddedEffects;if(donor?.m_effectPrefabs==null)return;var effects=new System.Collections.Generic.List<EffectList.EffectData>();foreach(var effect in donor.m_effectPrefabs){if(!effect.m_enabled||effect.m_prefab==null)continue;bool audio=effect.m_prefab.GetComponentInChildren<AudioSource>(true)!=null;if(audio?MasteryPlugin.Settings.EnablePerkSFX.Value:MasteryPlugin.Settings.EnablePerkProcVFX.Value)effects.Add(effect);}if(effects.Count!=0)new EffectList{m_effectPrefabs=effects.ToArray()}.Create(fire.transform.position,fire.transform.rotation,null,1,-1);}catch(Exception error){MasteryPlugin.Log.LogWarning("[MasterIdols] Native refill cue skipped: "+error.Message);}}
}
}
