using System;using System.Collections.Generic;using UnityEngine;
namespace ValheimMastery{
internal static class MasterIdolResidentHealing{
 internal static readonly int HealHash="SE_Greydwarf_shaman_heal".GetStableHashCode();
 internal static bool NativeStatusReady(){var status=ObjectDB.instance?.GetStatusEffect(HealHash) as SE_Stats;return status!=null&&Mathf.Abs(status.m_ttl-4)<.001f&&Mathf.Abs(status.m_healthOverTime-20)<.001f&&Mathf.Abs(status.m_healthOverTimeInterval-.5f)<.001f&&Mathf.Abs(status.m_healthOverTimeDuration)<.001f;}
 internal static int Select(Character caster,Collider[] hits,List<Character> result){result.Clear();if(!NativeStatusReady()||!MasterIdolResidentPolicy.Shaman(caster,out _)||!MasterIdolActivity.Near(caster.transform.position)||!MasterIdolResidentBudget.Scan())return 0;int mask=LayerMask.GetMask("character","character_net","character_ghost");if(mask==0)return 0;int count=Physics.OverlapSphereNonAlloc(caster.transform.position,4,hits,mask,QueryTriggerInteraction.Ignore);if(count>=hits.Length){MasterIdolResidentMetrics.Count("heal.scan-saturated");return 0;}for(int n=0;n<count;n++){var other=hits[n]?.GetComponentInParent<Character>();if(MasterIdolResidentPolicy.HealRecipient(caster,other)&&!result.Contains(other))result.Add(other);}result.Sort((a,b)=>{int distance=(a.transform.position-caster.transform.position).sqrMagnitude.CompareTo((b.transform.position-caster.transform.position).sqrMagnitude);return distance!=0?distance:string.CompareOrdinal(a.m_nview.GetZDO().m_uid.ToString(),b.m_nview.GetZDO().m_uid.ToString());});if(result.Count>3)result.RemoveRange(3,result.Count-3);return result.Count;}
 internal static bool Apply(Character caster,Character target){if(target?.m_nview?.IsOwner()!=true||!NativeStatusReady()||!MasterIdolResidentPolicy.HealRecipient(caster,target))return false;var manager=target.GetSEMan();if(manager==null||manager.HaveStatusEffect(HealHash))return false;var status=manager.AddStatusEffect(HealHash,false,0,0);if(status==null)return false;MasterIdolResidentMetrics.Count("heal.applied");return true;}
}
}
