using System;
using System.Collections.Generic;
using HarmonyLib;
using UnityEngine;
namespace ValheimMastery
{
    internal sealed class MasterIdolLight:MonoBehaviour
    {
        internal Fireplace Fire;internal ZNetView View;internal float Next;internal LinkedListNode<MasterIdolLight> Node;internal MasterIdolLighting.Order Pending;private ZNetView Registered;
        private void Awake(){Fire=GetComponent<Fireplace>();View=GetComponent<ZNetView>();}
        private void OnEnable(){MasterIdolLighting.Register(this);}
        internal void RegisterRpc(){if(View?.IsValid()==true&&Registered!=View){View.Register<ZPackage>(MasterIdolLighting.CommitRpc,(sender,packet)=>MasterIdolLighting.Commit(this,sender,packet));Registered=View;}}
        private void OnDisable(){MasterIdolLighting.Remove(this);}
        private void OnDestroy(){MasterIdolLighting.Remove(this);}
    }
    internal static class MasterIdolLighting
    {
        internal const string CommitRpc="VM_Idol_LightCommit_v1";
        private static readonly LinkedList<MasterIdolLight> Loaded=new LinkedList<MasterIdolLight>();private static float Next,WriteReset;private static int WriteCount;private static long Checks,Writes;
        internal static void Register(MasterIdolLight light){if(light.Node==null&&Loaded.Count<4096)light.Node=Loaded.AddLast(light);}
        internal static void Remove(MasterIdolLight light){if(light.Node!=null){Loaded.Remove(light.Node);light.Node=null;}light.Pending=null;}
        internal sealed class Order{internal string Nonce,Home;internal ZDO Fire,Actor;internal long ActorOwner,FireOwner;internal ushort ActorRevision,FireRevision;internal ZNet Session;internal ZDOMan Manager;internal ulong Generation;internal double Until,Started;}
        internal static bool Eligible(MasterIdolLight light,Character actor,string home)
        {
            if(light==null||light.Fire==null||light.View?.IsValid()!=true||actor?.m_nview?.IsValid()!=true||!ReferenceEquals(ZDOMan.instance?.GetZDO(light.View.GetZDO().m_uid),light.View.GetZDO())||!MasterIdolResidentPolicy.TryHome(actor,out var zone)||zone.Id!=home||!zone.Contains(light.transform.position)||!zone.Contains(actor.transform.position)||!MasterIdolActivity.Near(light.transform.position)||!MasterIdolActivity.Near(actor.transform.position)||MasterIdolSocialSeats.Battle(actor.GetComponent<BaseAI>(),actor)||actor.GetComponent<BaseAI>()?.IsSleeping()!=false)return false;
            var fire=light.Fire;var data=light.View.GetZDO();if(fire.m_infiniteFuel||!fire.m_canRefill||fire.m_fuelItem==null||data.GetInt(ZDOVars.s_state,1)==2||!MasterIdolResidentCycleRules.Refill(data.GetFloat(ZDOVars.s_fuel,0),fire.m_maxFuel))return false;bool resin=Utils.GetPrefabName(fire.m_fuelItem.gameObject)=="Resin";if(!MasterIdolResidentCycleRules.Role(Utils.GetPrefabName(actor.gameObject),resin))return false;
            int slash=home.IndexOf('/');if(slash<=0||!MasterIdolNetworkQuota.TryUid(home.Substring(0,slash),out long user,out uint id))return false;var idol=ZDOMan.instance?.GetZDO(new ZDOID(user,id));if(idol==null||MasterIdolWorldRegistry.Profile(idol.GetPrefab())?.Id!="BlackForest"||idol.GetString(MasterIdolWorldRegistry.TokenKey,"")!=home.Substring(slash+1)||!idol.GetBool(MasterIdolWorldRegistry.ActiveKey,false)||!idol.GetBool(MasterIdolWorldRegistry.BoundKey,false)||!MasterIdolToggleRules.On(idol.GetInt(MasterIdolWorldRegistry.SwitchKey,0)))return false;long creator=idol.GetLong(ZDOVars.s_creator,0);return creator!=0&&MasterIdolEffectZones.Allows(creator,light.transform.position)&&MasterIdolEffectZones.Allows(creator,actor.transform.position);
        }
        internal static string Describe()=>"lighting loaded="+Loaded.Count+" checks="+Checks+" writes="+Writes+" budget=8checks/2commits per0.5s; work=reachable walk/shaman safe ignition";
        internal static void Tick(){if(Time.unscaledTime<Next)return;Next=Time.unscaledTime+.5f;if(!MasterIdolEffectZones.Ready)return;int budget=Math.Min(8,Loaded.Count);for(int n=0;n<budget;n++){var light=Loaded.First.Value;Loaded.RemoveFirst();light.Node=Loaded.AddLast(light);if(light==null||light.Fire==null||light.View?.IsValid()!=true||!light.View.IsOwner())continue;light.RegisterRpc();if(light.Pending!=null){var order=light.Pending;if(order.Session!=ZNet.instance||order.Manager!=ZDOMan.instance||order.Generation!=MasterIdolLoadIdentity.Generation||ZNet.instance.GetTimeSeconds()>order.Until||!ReferenceEquals(light.View.GetZDO(),order.Fire)||order.Fire.GetOwner()!=order.FireOwner||order.Fire.OwnerRevision!=order.FireRevision)light.Pending=null;else continue;}if(Time.unscaledTime<light.Next)continue;light.Next=Time.unscaledTime+5;Checks++;var zone=MasterIdolEffectZones.At("BlackForest",light.transform.position);if(zone==null)continue;Character best=null;float score=float.MaxValue;foreach(var member in zone.Residents){if(!MasterIdolNetworkQuota.TryUid(member.Key,out long user,out uint id))continue;var actor=ZNetScene.instance?.FindInstance(new ZDOID(user,id))?.GetComponent<Character>();if(!Eligible(light,actor,zone.Id)||MasterIdolResidentWork.Busy(actor)||(actor.transform.position-light.transform.position).sqrMagnitude>4096)continue;float priority=(actor.transform.position-light.transform.position).sqrMagnitude+(member.Value=="Greydwarf_Shaman"?0:10000);if(priority<score){best=actor;score=priority;}}if(best==null)continue;var data=best.m_nview.GetZDO();var fire=light.View.GetZDO();var orderNew=new Order{Nonce=Guid.NewGuid().ToString("N"),Home=zone.Id,Actor=data,Fire=fire,ActorOwner=data.GetOwner(),FireOwner=fire.GetOwner(),ActorRevision=data.OwnerRevision,FireRevision=fire.OwnerRevision,Session=ZNet.instance,Manager=ZDOMan.instance,Generation=MasterIdolLoadIdentity.Generation,Started=ZNet.instance.GetTimeSeconds(),Until=ZNet.instance.GetTimeSeconds()+30};light.Pending=orderNew;var worker=best.GetComponent<MasterIdolResidentWork>();if(worker==null||!worker.Request(light,orderNew.Nonce,zone.Id))light.Pending=null;else MasterIdolResidentMetrics.Count("work.order-issued");}}
        private static bool WritePermit(){if(Time.unscaledTime>=WriteReset){WriteReset=Time.unscaledTime+.5f;WriteCount=0;}if(WriteCount>=2)return false;WriteCount++;return true;}
        internal static void Commit(MasterIdolLight light,long sender,ZPackage packet){try{var order=light.Pending;if(order==null||packet==null||packet.Size()>384||light.View?.IsOwner()!=true||order.Session!=ZNet.instance||order.Manager!=ZDOMan.instance||order.Generation!=MasterIdolLoadIdentity.Generation||!ReferenceEquals(light.View.GetZDO(),order.Fire)||order.Fire.GetOwner()!=order.FireOwner||order.Fire.OwnerRevision!=order.FireRevision)return;long world=packet.ReadLong();var uid=MasterIdolResidentWork.ReadUid(packet);int epoch=packet.ReadInt();string home=packet.ReadString(),nonce=packet.ReadString();bool noPath=packet.ReadBool();long started=packet.ReadLong(),now=ZNet.instance.GetTime().Ticks;if(packet.GetPos()!=packet.Size()||world!=ZNet.instance.GetWorldUID()||uid!=order.Actor.m_uid||nonce!=order.Nonce||home!=order.Home||sender!=order.ActorOwner||epoch!=order.ActorRevision||order.Actor.GetOwner()!=sender||order.Actor.OwnerRevision!=epoch||!ReferenceEquals(ZDOMan.instance.GetZDO(uid),order.Actor)||ZNet.instance.GetTimeSeconds()>order.Until||started>now+TimeSpan.TicksPerSecond||now-started>5*TimeSpan.TicksPerSecond)return;var actor=ZNetScene.instance?.FindInstance(uid)?.GetComponent<Character>();bool valid=Eligible(light,actor,home)&&(!noPath?(actor.transform.position-light.transform.position).sqrMagnitude<=16:MasterIdolResidentPolicy.Shaman(actor,out _)&&ZNet.instance.GetTimeSeconds()-order.Started>=1.264334&&MasterIdolResidentPresentation.ResourcesReady(actor,true));if(!valid){light.Pending=null;if(actor!=null)MasterIdolResidentWork.Result(actor,order.FireOwner,nonce,false);return;}if(!WritePermit())return;float before=order.Fire.GetFloat(ZDOVars.s_fuel,0),after=light.Fire.m_maxFuel;order.Fire.Set(ZDOVars.s_fuel,after);light.Pending=null;Writes++;MasterIdolResidentMetrics.Count("work.refill-committed");try{light.Fire.UpdateState();}catch(Exception){MasterIdolResidentMetrics.Count("work.state-display-failed");}try{MasterIdolResidentPresentation.Refuelled(light.Fire,before,after);}catch(Exception){MasterIdolResidentMetrics.Count("work.refill-fx-failed");}MasterIdolResidentWork.Result(actor,order.FireOwner,nonce,true);}catch(Exception){MasterIdolResidentMetrics.Count("work.commit-rejected");}}
    }
    [HarmonyPatch(typeof(Fireplace),"Awake")]
    internal static class MasterIdolLightAttach
    {private static void Postfix(Fireplace __instance){if(__instance.GetComponent<MasterIdolLight>()==null)__instance.gameObject.AddComponent<MasterIdolLight>();}}
    [HarmonyPatch(typeof(MasteryPlugin),"Update")]
    internal static class MasterIdolLightTick
    {private static void Postfix(){try{MasterIdolTiming.Measure("lighting.batch",()=>{MasterIdolLighting.Tick();return true;});}catch(Exception error){MasteryPlugin.Log.LogWarning("[MasterIdols] Lighting deferred: "+error.Message);}}}
}


