using System;using System.Collections.Generic;using HarmonyLib;using UnityEngine;
namespace ValheimMastery{
internal sealed class MasterIdolResidentWork:MonoBehaviour{
 private const string HealRpc="VM_Idol_ResidentHeal_v1",WorkRpc="VM_Idol_ResidentWork_v1",ResultRpc="VM_Idol_ResidentResult_v1",SpotRpc="VM_Idol_ResidentSpot_v1",CueRpc="VM_Idol_ResidentCue_v1";
 private Character Actor;private BaseAI Ai;private ZNetView View,Registered;private ZDO Data;private ZNet Session;private ZDOMan Manager;private ulong Generation;private long ObservedOwner;private ushort ObservedRevision;private float Next,Hold;private double NextHeal;private long LastHeal,ContextTicks,LastSpotTicks;private string LastSpotNonce;private bool LastSpotTerminal;private string LastHealNonce,LastCue;private Collider[] HealHits;private readonly List<Character> HealTargets=new List<Character>(3);
 private sealed class Job{internal MasterIdolLight Light;internal ZDO FireData,ActorData;internal long FireOwner,ActorOwner;internal ushort FireRevision,ActorRevision;internal string Nonce,Home;internal double Until;internal Vector3 FirePoint,Goal;internal List<Vector3> Route=new List<Vector3>();internal readonly List<MasterIdolSocialRoutes.Interval> Ranges=new List<MasterIdolSocialRoutes.Interval>();internal int Step;internal bool Planned,NoPath,Sent;internal float CueAt,Retry;}
 private Job Current;
 private void Awake(){Actor=GetComponent<Character>();Ai=GetComponent<BaseAI>();View=GetComponent<ZNetView>();}
 private void Register(){if(View?.IsValid()!=true||ReferenceEquals(Registered,View))return;View.Register<ZPackage>(HealRpc,ReceiveHeal);View.Register<ZPackage>(WorkRpc,ReceiveWork);View.Register<ZPackage>(ResultRpc,ReceiveResult);View.Register<ZPackage>(SpotRpc,ReceiveSpot);View.Register<ZPackage>(CueRpc,ReceiveCue);Registered=View;}
 private bool Context(){Register();if(View?.IsValid()!=true||ZNet.instance?.GetWorld()==null)return false;var data=View.GetZDO();long owner=data.GetOwner();ushort revision=data.OwnerRevision;bool changed=!ReferenceEquals(Data,data)||Session!=ZNet.instance||Manager!=ZDOMan.instance||Generation!=MasterIdolLoadIdentity.Generation||ObservedOwner!=owner||ObservedRevision!=revision;if(changed){Data=data;Session=ZNet.instance;Manager=ZDOMan.instance;Generation=MasterIdolLoadIdentity.Generation;ObservedOwner=owner;ObservedRevision=revision;Cancel(true);NextHeal=ZNet.instance.GetTimeSeconds()+10;ContextTicks=ZNet.instance.GetTime().Ticks;LastHeal=LastSpotTicks=0;LastSpotNonce=null;LastSpotTerminal=false;LastHealNonce=LastCue=null;}return ReferenceEquals(ZDOMan.instance?.GetZDO(data.m_uid),data);}
 private bool Peace=>Actor!=null&&Ai!=null&&!MasterIdolSocialSeats.Battle(Ai,Actor)&&!Ai.IsSleeping()&&!Actor.InDodge()&&!Actor.InEmote()&&GetComponent<MasterIdolWelcome>()?.IsPresenting!=true;
 internal static bool Busy(Character actor){var work=actor?.GetComponent<MasterIdolResidentWork>();return work!=null&&(work.Current!=null||Time.unscaledTime<work.Hold||work.GetComponent<MasterIdolResidentPresentation>()?.Playing==true);}
 internal static bool Idle(Character actor,float dt){var work=actor?.GetComponent<MasterIdolResidentWork>();return work!=null&&work.Step(dt);}
 private void Update(){if(!Context())return;if(Time.deltaTime<=0||Time.unscaledTime<Next)return;Next=Time.unscaledTime+.25f;if(!View.IsOwner())return;if(!MasterIdolResidentPolicy.TryHome(Actor,out _)||!Peace||!MasterIdolActivity.Near(transform.position)){Cancel(true);return;}if(Current!=null){if(!Valid(Current)||ZNet.instance.GetTimeSeconds()>Current.Until)Cancel(true);return;}if(Busy(Actor)||!MasterIdolResidentPolicy.Shaman(Actor,out _)||ZNet.instance.GetTimeSeconds()<NextHeal)return;HealHits=HealHits??new Collider[64];int count=MasterIdolResidentHealing.Select(Actor,HealHits,HealTargets);if(count==0){MasterIdolResidentMetrics.Count("heal.no-targets");NextHeal=ZNet.instance.GetTimeSeconds()+1;return;}NextHeal=ZNet.instance.GetTimeSeconds()+10;var packet=Header(MasterIdolEffectZones.ResidentHome(Data.m_uid.ToString(),Utils.GetPrefabName(gameObject)).Id,Guid.NewGuid().ToString("N"));packet.Write(count);foreach(var target in HealTargets)WriteUid(packet,target.m_nview.GetZDO().m_uid);View.InvokeRPC(ZNetView.Everybody,HealRpc,packet);MasterIdolResidentMetrics.Count("heal.broadcast");}
 private ZPackage Header(string home,string nonce){var packet=new ZPackage();packet.Write(ZNet.instance.GetWorldUID());WriteUid(packet,View.GetZDO().m_uid);packet.Write((int)View.GetZDO().OwnerRevision);packet.Write(home);packet.Write(nonce);packet.Write(ZNet.instance.GetTime().Ticks);return packet;}
 private bool Read(long sender,ZPackage packet,out string home,out string nonce,out long ticks){home=nonce=null;ticks=0;if(packet==null||packet.Size()>512||!Context()||sender!=Data.GetOwner())return false;long world=packet.ReadLong();var uid=ReadUid(packet);int epoch=packet.ReadInt();home=packet.ReadString();nonce=packet.ReadString();ticks=packet.ReadLong();long now=ZNet.instance.GetTime().Ticks;return world==ZNet.instance.GetWorldUID()&&uid==Data.m_uid&&epoch==Data.OwnerRevision&&home.Length<=128&&Guid.TryParseExact(nonce,"N",out _)&&ticks>ContextTicks+TimeSpan.TicksPerSecond&&ticks<=now+TimeSpan.TicksPerSecond&&now-ticks<=5*TimeSpan.TicksPerSecond&&MasterIdolResidentPolicy.TryHome(Actor,out var zone)&&zone.Id==home;}
 private void ReceiveHeal(long sender,ZPackage packet){try{if(!Read(sender,packet,out var home,out var nonce,out long ticks)||!MasterIdolResidentPolicy.Shaman(Actor,out _))return;int count=packet.ReadInt();if(count<1||count>3)return;var targets=new ZDOID[count];for(int n=0;n<count;n++){targets[n]=ReadUid(packet);for(int k=0;k<n;k++)if(targets[k]==targets[n])return;}if(packet.GetPos()!=packet.Size()||LastHealNonce==nonce||LastHeal!=0&&ticks-LastHeal<10*TimeSpan.TicksPerSecond)return;LastHeal=ticks;LastHealNonce=nonce;for(int n=0;n<count;n++){var target=ZNetScene.instance?.FindInstance(targets[n])?.GetComponent<Character>();MasterIdolResidentHealing.Apply(Actor,target);}Hold=Time.unscaledTime+Mathf.Max(0,2.266667f-Mathf.Max(0,(float)((ZNet.instance.GetTime().Ticks-ticks)/(double)TimeSpan.TicksPerSecond)));if(MasteryPlugin.Settings.EnablePerkProcVFX.Value)(GetComponent<MasterIdolResidentPresentation>()??gameObject.AddComponent<MasterIdolResidentPresentation>()).Begin(false,Mathf.Max(0,(float)((ZNet.instance.GetTime().Ticks-ticks)/(double)TimeSpan.TicksPerSecond)),home);else MasterIdolResidentMetrics.Count("cue.denied.vfx-disabled");}catch(Exception){MasterIdolResidentMetrics.Count("heal.packet-rejected");}}
 internal void Spot(string home,string nonce,Vector3 point,float duration,bool work,bool enable){if(!Context()||!View.IsOwner())return;var packet=Header(home,nonce);packet.Write(enable);packet.Write(point);packet.Write(duration);packet.Write(work);View.InvokeRPC(ZNetView.Everybody,SpotRpc,packet);}
 private void ReceiveSpot(long sender,ZPackage packet){try{if(!Read(sender,packet,out var home,out var nonce,out long ticks))return;bool enabled=packet.ReadBool();var point=packet.ReadVector3();float duration=packet.ReadSingle();bool work=packet.ReadBool();if(packet.GetPos()!=packet.Size()||!Finite(point)||!float.IsFinite(duration)||duration<0||duration>30)return;if(ticks<LastSpotTicks||ticks==LastSpotTicks&&nonce!=LastSpotNonce||nonce==LastSpotNonce&&(LastSpotTerminal||enabled&&ticks==LastSpotTicks))return;LastSpotTicks=ticks;LastSpotNonce=nonce;LastSpotTerminal=!enabled;double remaining=duration-(ZNet.instance.GetTime().Ticks-ticks)/(double)TimeSpan.TicksPerSecond;if(enabled&&remaining>0)MasterIdolResidentSpacing.Put(Actor,home,nonce,point,ZNet.instance.GetTimeSeconds()+remaining,work);else MasterIdolResidentSpacing.Remove(Actor,home,nonce);}catch(Exception){MasterIdolResidentMetrics.Count("spot.packet-rejected");}}
 internal bool Request(MasterIdolLight light,string nonce,string home){if(!Context()||light?.View?.IsOwner()!=true||Busy(Actor)||!Peace)return false;var packet=new ZPackage();packet.Write(ZNet.instance.GetWorldUID());WriteUid(packet,light.View.GetZDO().m_uid);packet.Write((int)light.View.GetZDO().OwnerRevision);packet.Write(home);packet.Write(nonce);packet.Write(ZNet.instance.GetTime().Ticks);View.InvokeRPC(Data.GetOwner(),WorkRpc,packet);return true;}
 private void ReceiveWork(long sender,ZPackage packet){try{if(packet==null||packet.Size()>384||!Context()||!View.IsOwner()||!Peace||Busy(Actor)||!MasterIdolActivity.Near(transform.position))return;long world=packet.ReadLong();var id=ReadUid(packet);int epoch=packet.ReadInt();string home=packet.ReadString(),nonce=packet.ReadString();long started=packet.ReadLong(),now=ZNet.instance.GetTime().Ticks;if(packet.GetPos()!=packet.Size()||world!=ZNet.instance.GetWorldUID()||home.Length>128||!Guid.TryParseExact(nonce,"N",out _)||started<=ContextTicks+TimeSpan.TicksPerSecond||started>now+TimeSpan.TicksPerSecond||now-started>5*TimeSpan.TicksPerSecond)return;var light=ZNetScene.instance?.FindInstance(id)?.GetComponent<MasterIdolLight>();if(light?.View?.IsValid()!=true||light.View.GetZDO().GetOwner()!=sender||light.View.GetZDO().OwnerRevision!=epoch||!MasterIdolLighting.Eligible(light,Actor,home))return;GetComponent<MasterIdolSocialSeats>()?.Stop();Current=new Job{Light=light,FireData=light.View.GetZDO(),ActorData=Data,FireOwner=sender,ActorOwner=Data.GetOwner(),FireRevision=light.View.GetZDO().OwnerRevision,ActorRevision=Data.OwnerRevision,Nonce=nonce,Home=home,Until=ZNet.instance.GetTimeSeconds()+30,FirePoint=light.transform.position};Spot(home,nonce,light.transform.position,30,true,true);MasterIdolResidentMetrics.Count("work.order-accepted");}catch(Exception){MasterIdolResidentMetrics.Count("work.packet-rejected");}}
 private bool Valid(Job job){return Context()&&View.IsOwner()&&Peace&&MasterIdolActivity.Near(transform.position)&&ReferenceEquals(Data,job.ActorData)&&Data.GetOwner()==job.ActorOwner&&Data.OwnerRevision==job.ActorRevision&&job.Light?.View?.IsValid()==true&&ReferenceEquals(job.Light.View.GetZDO(),job.FireData)&&job.FireData.GetOwner()==job.FireOwner&&job.FireData.OwnerRevision==job.FireRevision&&(job.Light.transform.position-job.FirePoint).sqrMagnitude<.01f&&MasterIdolLighting.Eligible(job.Light,Actor,job.Home);}
 private bool Plan(Job job){var zone=MasterIdolEffectZones.Find(job.Home);if(zone==null||Pathfinding.instance==null||ZoneSystem.instance==null)return false;int failed=0;for(int n=0;n<3;n++){Vector3 offset=transform.position-job.FirePoint;offset.y=0;if(offset.sqrMagnitude<.01f)offset=Vector3.forward;float angle=n*120f;var direction=Quaternion.AngleAxis(angle,Vector3.up)*offset.normalized;var goal=job.FirePoint+direction*2.5f;if(!ZoneSystem.instance.IsZoneLoaded(goal))return false;if(!zone.Contains(goal))return false;if(!MasterIdolResidentBudget.Path())return false;job.Route.Clear();if(Pathfinding.instance.GetPath(transform.position,goal,job.Route,Ai.m_pathAgentType,true,false,false)&&MasterIdolSocialRoutes.Inside(zone,transform.position,goal,job.Route,job.Ranges)){float length=0;var last=transform.position;foreach(var corner in job.Route){length+=Vector3.Distance(last,corner);last=corner;}length+=Vector3.Distance(last,goal);if(length>128)return false;job.Goal=goal;job.Planned=true;MasterIdolResidentMetrics.Count("work.path-found");return true;}failed++;}if(failed==3&&MasterIdolResidentPolicy.Shaman(Actor,out _)&&MasterIdolResidentPresentation.ResourcesReady(Actor,true)){job.Planned=job.NoPath=true;job.CueAt=Time.unscaledTime;Hold=Time.unscaledTime+3.333334f;var packet=Header(job.Home,job.Nonce);WriteUid(packet,job.FireData.m_uid);View.InvokeRPC(ZNetView.Everybody,CueRpc,packet);MasterIdolResidentMetrics.Count("work.ignite-no-path");return true;}return false;}
 private bool Step(float dt){if(!Context()||!View.IsOwner()||!Peace)return false;if(Current==null){if(Time.unscaledTime<Hold||GetComponent<MasterIdolResidentPresentation>()?.Playing==true){Ai.StopMoving();return true;}return false;}var job=Current;if(!Valid(job)||ZNet.instance.GetTimeSeconds()>job.Until){Cancel(true);return false;}if(!job.Planned){if(Time.unscaledTime>=job.Retry){job.Retry=Time.unscaledTime+.5f;Plan(job);}Ai.StopMoving();return true;}if(job.NoPath){Ai.StopMoving();Ai.LookAt(job.FirePoint);if(Time.unscaledTime-job.CueAt<1.264334f)return true;}else{while(job.Step<job.Route.Count&&(transform.position-job.Route[job.Step]).sqrMagnitude<.36f)job.Step++;var next=job.Step<job.Route.Count?job.Route[job.Step]:job.Goal;var zone=MasterIdolEffectZones.Find(job.Home);if(!MasterIdolSocialRoutes.Inside(zone,transform.position,next,Array.Empty<Vector3>(),job.Ranges)){Cancel(true);return false;}if((transform.position-job.Goal).sqrMagnitude>1){Ai.MoveTo(dt,next,.6f,false);return true;}Ai.StopMoving();Ai.LookAt(job.FirePoint);}if(Time.unscaledTime>=job.Retry){job.Retry=Time.unscaledTime+.5f;SendCommit(job);}return true;}
 private void SendCommit(Job job){var packet=new ZPackage();packet.Write(ZNet.instance.GetWorldUID());WriteUid(packet,Data.m_uid);packet.Write((int)Data.OwnerRevision);packet.Write(job.Home);packet.Write(job.Nonce);packet.Write(job.NoPath);packet.Write(ZNet.instance.GetTime().Ticks);job.Light.View.InvokeRPC(job.FireOwner,MasterIdolLighting.CommitRpc,packet);job.Sent=true;}
 private void ReceiveResult(long sender,ZPackage packet){try{var job=Current;if(job==null||packet==null||packet.Size()>128||!Context()||!View.IsOwner()||!ReferenceEquals(Current,job)||sender!=job.FireOwner)return;string nonce=packet.ReadString();bool success=packet.ReadBool();if(packet.GetPos()!=packet.Size()||nonce!=job.Nonce)return;MasterIdolResidentMetrics.Count(success?"work.completed":"work.denied");Cancel(false);}catch(Exception){MasterIdolResidentMetrics.Count("work.result-rejected");}}
 internal static void Result(Character actor,long fireOwner,string nonce,bool success){var packet=new ZPackage();packet.Write(nonce);packet.Write(success);actor.m_nview.InvokeRPC(actor.m_nview.GetZDO().GetOwner(),ResultRpc,packet);}
 private void ReceiveCue(long sender,ZPackage packet){try{if(!Read(sender,packet,out var home,out var nonce,out var ticks)||nonce==LastCue||!MasterIdolResidentPolicy.Shaman(Actor,out _))return;var fireId=ReadUid(packet);if(packet.GetPos()!=packet.Size())return;var light=ZNetScene.instance?.FindInstance(fireId)?.GetComponent<MasterIdolLight>();if(!MasterIdolLighting.Eligible(light,Actor,home))return;LastCue=nonce;if(MasteryPlugin.Settings.EnablePerkProcVFX.Value)(GetComponent<MasterIdolResidentPresentation>()??gameObject.AddComponent<MasterIdolResidentPresentation>()).Begin(true,Mathf.Max(0,(float)((ZNet.instance.GetTime().Ticks-ticks)/(double)TimeSpan.TicksPerSecond)),home);}catch(Exception){MasterIdolResidentMetrics.Count("cue.packet-rejected");}}
 private void Cancel(bool stop){var job=Current;Current=null;if(job!=null){MasterIdolResidentSpacing.Remove(Actor,job.Home,job.Nonce);if(View?.IsValid()==true&&View.IsOwner()&&ReferenceEquals(View.GetZDO(),job.ActorData)&&job.ActorData.GetOwner()==job.ActorOwner&&job.ActorData.OwnerRevision==job.ActorRevision)Spot(job.Home,job.Nonce,job.FirePoint,0,true,false);}if(stop)GetComponent<MasterIdolResidentPresentation>()?.Stop();}
 private void OnDisable()=>Cancel(true);private void OnDestroy()=>Cancel(true);
 internal static void WriteUid(ZPackage packet,ZDOID id){packet.Write(id.UserID);packet.Write(id.ID);}internal static ZDOID ReadUid(ZPackage packet)=>new ZDOID(packet.ReadLong(),packet.ReadUInt());private static bool Finite(Vector3 point)=>float.IsFinite(point.x)&&float.IsFinite(point.y)&&float.IsFinite(point.z);
 internal string Describe()=>"resident work="+(Current==null?"none":Current.NoPath?"safe-ignition":Current.Planned?"walking":"planning")+" healIn="+Math.Max(0,NextHeal-(ZNet.instance?.GetTimeSeconds()??0))+" registration="+(Registered!=null);
}
[HarmonyPatch(typeof(BaseAI),"Awake")]internal static class MasterIdolResidentWorkAttachPatch{private static void Postfix(BaseAI __instance){if(MasterIdolResidentRoster.Limit(Utils.GetPrefabName(__instance.gameObject))>0&&__instance.GetComponent<MasterIdolResidentWork>()==null)__instance.gameObject.AddComponent<MasterIdolResidentWork>();}}
}
