using UnityEngine;
namespace ValheimMastery{
internal static class MasterIdolResidentPolicy{
 internal static bool TryHome(Character actor,out MasterIdolEffectZone home){home=null;if(!GoldCraftingService.Enabled||actor==null||actor.IsDead()||actor.m_nview?.IsValid()!=true)return false;var zdo=actor.m_nview.GetZDO();if(zdo==null||!ReferenceEquals(ZDOMan.instance?.GetZDO(zdo.m_uid),zdo))return false;if(!MasterIdolNativeTaming.Assigned(zdo))return false;home=MasterIdolEffectZones.ResidentHome(zdo.m_uid.ToString(),Utils.GetPrefabName(actor.gameObject));return home!=null&&MasterIdolNativeTaming.SameHome(zdo.GetString(MasterIdolNativeTaming.HomeKey,""),home.Id);}
 // IsEnemy postfix must never call Leash.Refresh/Calm or BaseAI.IsEnemy recursively.
 internal static bool Friendly(Character actor,Character other){if(other==null)return false;if(MasterIdolNativeTaming.Friend(actor)&&(other is Player||other.IsTamed()||MasterIdolNativeTaming.Friend(other)))return true;if(!TryHome(actor,out var home))return false;if(other.IsTamed()||TryHome(other,out _))return true;if(other is Player player)return MasterIdolEffectZones.Allows(player.GetPlayerID(),actor.transform.position)&&MasterIdolEffectZones.Allows(player.GetPlayerID(),player.transform.position);return false;}
 internal static bool CurrentTarget(Character target)=>target!=null&&!target.IsDead()&&target.m_nview?.IsValid()==true&&ReferenceEquals(ZDOMan.instance?.GetZDO(target.m_nview.GetZDO().m_uid),target.m_nview.GetZDO());
 private static bool Wild(Character other)=>CurrentTarget(other)&&!other.IsTamed()&&MasterIdolResidents.Family(other)&&!TryHome(other,out _);
 internal static bool Enemy(Character first,Character second,bool native){if(Friendly(first,second)||Friendly(second,first))return false;bool a=TryHome(first,out var ha),b=TryHome(second,out var hb);if(a&&Friendly(first,second)||b&&Friendly(second,first))return false;if(a&&Wild(second)&&ha.Contains(first.transform.position,15)&&ha.Contains(second.transform.position,15)||b&&Wild(first)&&hb.Contains(second.transform.position,15)&&hb.Contains(first.transform.position,15))return true;return native;}
 internal static bool Shaman(Character actor,out MasterIdolEffectZone home)=>TryHome(actor,out home)&&Utils.GetPrefabName(actor.gameObject)=="Greydwarf_Shaman";
 internal static bool HealRecipient(Character caster,Character target){return Shaman(caster,out var home)&&target!=null&&!target.IsDead()&&target.m_nview?.IsValid()==true&&ReferenceEquals(ZDOMan.instance?.GetZDO(target.m_nview.GetZDO().m_uid),target.m_nview.GetZDO())&&home.Contains(caster.transform.position)&&home.Contains(target.transform.position)&&(caster.transform.position-target.transform.position).sqrMagnitude<=16&&Friendly(caster,target)&&(!(target is Player player)||MasterIdolEffectZones.Allows(player.GetPlayerID(),caster.transform.position)&&MasterIdolEffectZones.Allows(player.GetPlayerID(),player.transform.position))&&target.GetHealthPercentage()<1f&&target.GetSEMan()?.HaveStatusEffect(MasterIdolResidentHealing.HealHash)!=true;}
}
}
