using Mono.Cecil;
using Mono.Cecil.Cil;

if (args.Length != 2) throw new ArgumentException("Pass candidate DLL and its native assembly_valheim.dll.");
using var plugin = ModuleDefinition.ReadModule(args[0]);
using var native = ModuleDefinition.ReadModule(args[1]);
int passed = 0;
void Check(bool value, string text) { if (!value) throw new Exception(text); passed++; Console.WriteLine("PASS " + text); }
TypeDefinition Type(string name) => plugin.Types.Single(t => t.Name == name);
MethodDefinition Method(string type, string name) => Type(type).Methods.Single(m => m.Name == name);
IEnumerable<MethodReference> Calls(MethodDefinition method) => method.Body.Instructions.Select(i => i.Operand).OfType<MethodReference>();
bool Call(string type, string method, string target, string name) => Calls(Method(type, method)).Any(r => r.DeclaringType.Name == target && r.Name == name);
bool Text(string type, string method, string text) => Method(type, method).Body.Instructions.Any(i => i.OpCode == OpCodes.Ldstr && Equals(i.Operand, text));
bool Float(string type, string method, float value) => Method(type, method).Body.Instructions.Any(i => i.OpCode == OpCodes.Ldc_R4 && Equals(i.Operand, value));
Check(!Call("WorkshopRemoteCraft", "Preview", "WorkshopRemoteCraft", "get_ClientBusy") && !Call("WorkshopRemoteCraft", "Preview", "WorkshopRecovery", "get_Outstanding"), "Рецепт не стає недоступним через transient action/receipt");
Check(!Call("WorkshopStoragePreview", "Refresh", "WorkshopRemoteCraft", "get_ClientBusy") && !Call("WorkshopStoragePreview", "Refresh", "WorkshopRecovery", "get_Outstanding"), "Preview не обнуляє stock через транзакцію");
Check(Call("WorkshopStoragePreview", "Refresh", "WorkshopStoragePreview", "Invalidate"), "Очищення preview також спиняє старий cache expiry");
Check(Call("WorkshopRemoteCraft", "Reply", "WorkshopStoragePreview", "RefreshUiSoon") && Call("WorkshopRecovery", "Clear", "WorkshopStoragePreview", "RefreshUiSoon"), "Outcome та settlement планують актуалізацію рядків");
Check(Call("WorkshopStoragePreview", "Tick", "WorkshopRemoteCraft", "get_ClientBusy") && Call("WorkshopStoragePreview", "Tick", "WorkshopRecovery", "get_Outstanding") && Call("WorkshopStoragePreview", "Tick", "InventoryGui", "UpdateCraftingPanel"), "UI rebuild виконується після unwind/settlement");
Check(Float("WorkshopStoragePreview", "RefreshUiSoon", 1.25f) && Float("WorkshopStoragePreview", "Tick", .25f), "Refresh повтори обмежено1.25с/250мс");
Check(Call("WorkshopNetworkStorage", "FindEligibleCore", "WorkshopNetworkStorage", "CanObserve") && Call("WorkshopNetworkStorage", "FindEligibleCore", "Container", "CheckAccess"), "Readonly UI і реальна access policy мають окремі гілки");
Check(Call("WorkshopNetworkStorage", "FindEligibleCore", "WorkshopNetworkStorage", "WardAllows") && Call("WorkshopNetworkStorage", "FindEligibleCore", "WorkshopNetwork", "CoveredComponent") && Call("WorkshopNetworkStorage", "CanObserve", "ZDO", "GetBool") && Call("WorkshopNetworkStorage", "CanObserve", "ZDO", "GetLong"), "Приватність/creator/ward/coverage/quarantine лишилися");
Check(Call("WorkshopRemoteCraft", "AllowCraft", "WorkshopRemoteCraft", "get_ClientBusy") && Call("WorkshopRemoteCraft", "BeginBuild", "WorkshopRecovery", "get_Outstanding") && Call("WorkshopRemoteCraft", "CommitRequest", "WorkshopAtomicDebit", "Begin"), "UI доступність не є debit/output permission");
var before = Method("WorkshopBuildBridge", "BeforePlace");
int Index(MethodDefinition method, string name) => method.Body.Instructions.ToList().FindIndex(i => i.Operand is MethodReference r && r.Name == name);
Check(Index(before, "get_ClientBusy") >= 0 && Index(before, "get_ClientBusy") < Index(before, "TryBuild"), "Повторний build не минає busy через personal shortcut");
Check(Method("WorkshopBuildRequirementsPatch", "Postfix").Body.Instructions.Any(i => i.Operand is FieldReference f && f.Name == "PlacementDepth") && Call("WorkshopBuildRequirementsPatch", "Postfix", "WorkshopRemoteCraft", "TryResourceCosts"), "Native admission лише в placement scope для підтриманих costs");
Check(Method("WorkshopBuildAdmissionScopePatch", "Finalizer").Body.Instructions.Any(i => i.Operand is FieldReference f && f.Name == "PlacementDepth"), "Scope cleanup є на exception exit");
Check(Call("WorkshopBuildRequestPatch", "Prefix", "WorkshopBuildBridge", "BeforePlace") && Method("WorkshopBuildRequestPatch", "Prefix").Body.Instructions.Count(i => i.OpCode == OpCodes.Ldc_I4_0) >= 2, "Очікування не підміняє native placement success");
var placement = native.Types.Single(t => t.Name == "Player").Methods.Single(m => m.Name == "UpdatePlacement");
var code = placement.Body.Instructions.ToList();
int requirement = Index(placement, "HaveRequirements"), place = Index(placement, "TryPlacePiece");
int missing = code.FindIndex(i => i.OpCode == OpCodes.Ldstr && Equals(i.Operand, "$msg_missingrequirement"));
Check(requirement >= 0 && requirement < place && place < missing, "Native missing feedback перед async bridge: причина підтверджена");
Check(code[requirement + 1].Operand is Instruction missingTarget && missingTarget.Offset <= code[missing].Offset && code[place + 1].Operand is Instruction waitTarget && waitTarget.Offset > code[missing].Offset, "TryPlacePiece=false обходить і consumption, і missing feedback");
var gui = native.Types.Single(t => t.Name == "InventoryGui");
Check(Calls(gui.Methods.Single(m => m.Name == "DoCrafting")).Any(r => r.Name == "UpdateCraftingPanel"), "Native DoCrafting перебудовує рядки всередині executing scope");
Check(Text("RoadRhythmPhaseVisual", "ResolveLandingPrefab", "fx_perfectdodge") && Text("RoadRhythmPhaseVisual", "EmitPhase", "jump_70_air"), "Run використовує точний air-jump donor та reference scale");
Check(Call("VfxRecipeService", "Play", "RoadRhythmPhaseVisual", "Set") && Text("VfxRecipeService", "Play", "run_70_stack3"), "Natural Run feedback справді викликає новий phase visual");
Check(Call("RoadRhythmPhaseVisual", "EmitPhase", "NativeMovementPulse", "Schedule") && !Call("RoadRhythmPhaseVisual", "EmitPhase", "NativeLandingBurst", "Schedule"), "Run selective scheduler відокремлений від legacy autoring");
Check(Float("RoadRhythmPhaseVisual", "EmitPhase", 90f) && Float("RoadRhythmPhaseVisual", "EmitPhase", .9f) && Float("RoadRhythmPhaseVisual", "EmitPhase", .95f), "Круг вертикальний: phase2 трохи менший, torso anchor");
Check(Text("NativeMovementPulse", "Schedule", "run_70_stack1") && Text("NativeMovementPulse", "Schedule", "run_70_stack3") && Float("NativeMovementPulse", "Schedule", .9f) && Float("NativeMovementPulse", "Schedule", 1.8f), "Run phases мають окремий ring count/alpha/lifetime branch");
Check(Float("NativeMovementPulse", "Schedule", .72f) && Float("NativeMovementPulse", "Schedule", 1.5f) && Call("NativeMovementPulse", "PlayAirJump", "VfxRecipeService", "Spawn"), "Air jump зберігає чинні tuning та spawn route");
Check(Call("NativeMovementPulse", "Schedule", "NativeBurstPlayback", "Mute") && Call("NativeMovementPulse", "Schedule", "NativeVfxSafeFrame", "AfterReady") && Call("NativeMovementPulse", "EmitReady", "NativeBurstPlayback", "EmitOnce"), "Cold pooled VFX: mute перед readiness, один контрольований burst");
Console.WriteLine($"PASS {passed} static/native contracts; live UI/visuals require separate verification.");
